config/routes.rb
Rails.application.routes.draw do
  
  #get 'relationships/create'
  #get 'relationships/destory'
  #get 'book_comments/create'
  #get 'book_comments/destroy'
  #get 'favorites/create'
  #get 'favorites/destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  
  get "home/about"=>"homes#about"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources:book_comments, only:[:create,:destroy]
  end    
  
  resources :users, only: [:index,:show,:edit,:update] do
    get :following
    get :followed
  end  
  
  get 'relationships/create'
  get 'relationships/destroy'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get '/search' => 'search#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
 
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
    
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
  validates :comment, presence: true
end

app/models/book_view.rb
class BookView < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one :favorite
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :book, optional: true
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, presence: true, on: :update
 
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :followed, source: :follower
  has_many :follower_user, through: :follower, source: :followed
    
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    follower_user.include?(user)
  end
    
  def favorited?
    favorite.present?
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]
  
  def show
    @book = Book.find(params[:id])
    #@post = @book.favorites.post.present? ? @book.favorites.post : Post.new
    #@favorite = current_user.favorite
    #@post = current_user.favorite.post.present? ? current_user.favorite.post : Post.new
    @comment = BookComment.new
    @book_new = Book.new
    @user = @book.user
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id 
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: [:about]
  
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_action :authenticate_user!

  def room
    @user = current_user
    #@messages = Message.all
    @messages = Message.where(room_id: User.find(current_user.id).entries.first.room.id)
    @message = Message.new
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def search
        @model = params["search"]["model"]
        @content = params["search"]["content"]
        @method = params["search"]["method"]
        @records = search_for(@model,@content,@method) #@user@bookの情報が入っている
    end

    private

    def search_for(model,content,method)
        if model == 'user'
            if method == 'perfect_match' #完全一致
               User.where('name LIKE ?', content) #モデル名.where('カラム名 LIKE?', 条件に合わせた中身)
            elsif method == 'forward_match' #前方一致
               User.where('name LIKE ?', content+'%')
            elsif method == 'backward_match' #後方一致
               User.where('name LIKE ?', '%'+content)
            elsif method == 'partial' #部分一致
               User.where('name LIKE ?', '%'+content+'%')
            end
        else
            if method == 'perfect_match'
               Book.where('title LIKE ?', content)
            elsif method == 'forward_match'
               Book.where('title LIKE ?', content+'%')
            elsif method == 'backward_match'
               Book.where('title LIKE ?', '%'+content)
            elsif method == 'partial'
               Book.where('title LIKE ?', '%'+content+'%')
            end
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @books = Book.all
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end
  
  def edit
    @user = current_user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def following
    @user = User.find(params[:user_id])
  end

  def followed
    @user = User.find(params[:user_id])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <!--フォロー機能-->
        <% "id: #{user.id}" %>
        <td><%= "フォロー数: #{user.follower.count}" %></td>
        <td><%= "フォロワー数: #{user.followed.count}" %></td>

        <% unless user == current_user %> <!--自分は表示しない-->
          <% if current_user.following?(user) %>
            <td><%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %></td>
          <% else %>
            <td><%= link_to 'フォローする', follow_path(user.id), method: :post %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>コメント数</th>
	  <th><%= user.book_comments.count %></th>
  </tr>
  <tr>
    <th>フォロー数</th> 
    <th><%= link_to "#{user.follower.count}", user_following_path(user.id) %><%#= user.follower.count %></th>
  </tr>
  <tr>
    <th>フォロワー数</th>
    <th><%=link_to "#{user.followed.count}", user_followed_path(user.id) %><%#= user.followed.count %></th>
  </tr>
  <% unless user == current_user %>
    <tr>
      <!--自分は表示しない-->
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :post, class: "btn btn-info", style: "margin-left: 30px;" %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :post, class: "btn btn-success", style: "margin-left: 30px;" %>
      <% end %>
    </tr>
  <% end %>
</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followed.html.erb
<!--フォロワー一覧-->

<div class="body">
  <div class="container">
    <div class="row">

      <h1>Follower Users</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>

        <tbody>
          <% @user.following_user.each do |user| %>
            <tr>
              <td>
                <%#= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              </td>
              <td><%= user.name %></td>
              <% "id: #{user.id}" %>
              <td><%= "フォロー数: #{user.follower.count}" %></td>
              <td><%= "フォロワー数: #{user.followed.count}" %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<!--フォロー一覧-->

<div class="body">
  <div class="container">
    <div class="row">

      <h1>Follow Users</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>

        <tbody>
          <% @user.follower_user.each do |user| %>
            <tr>
              <td>
                <%#= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              </td>
              <td><%= user.name %></td>
              <% "id: #{user.id}" %>
              <td><%= "フォロー数: #{user.follower.count}" %></td>
              <td><%= "フォロワー数: #{user.followed.count}" %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>  
  </div>
</div>

app/views/users/room.html.erb
<!--フォロー一覧-->

<div class="body">
  <div class="container">
    <div>
      <h1>メッセージ一覧</h1>
      <div id="chat_area">
        <%= render "messages/chat_list", messages: @messages %>
      </div>
      <div id="chat_form">
        <%= render "messages/chat_form", room: @room, message: @message %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>